trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: "Fase 1 - Build"
  jobs:
  - job: BuildJob
    steps:
    - script: dotnet --version
      displayName: "Ver versão do .NET"

    - script: dotnet restore || echo "Falha no restore (simulada)"
      displayName: "Restaurar dependências"

    - script: dotnet build || echo "Falha no build (simulada)"
      displayName: "Compilar projeto"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: .
        ArtifactName: dotnetBuild
      displayName: "Publicar arquivos do build"

- stage: Test
  displayName: "Fase 2 - Teste"
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - download: current
      artifact: dotnetBuild
      displayName: "Baixar artifact do build"

    - script: |
        echo "Iniciando testes .NET..."
        dotnet test || echo "⚠️ Nenhum teste encontrado. Simulação realizada."
      displayName: 'Executar testes .NET'

- stage: Deploy
  displayName: "Fase 3 - Deploy"
  dependsOn: Test
  jobs:
  - job: DeployJob
    steps:
    - download: current
      artifact: dotnetBuild
      displayName: "Baixar artifact do build"

    - script: |
      echo "Simulando deploy .NET..."
      mkdir deploy
      echo "Deploy fictício" > deploy\resultado.txt
      echo "Deploy .NET simulado com sucesso."
  displayName: 'Simular Deploy .NET'
